INSERT INTO moviemood.PELICULAS (pelicula_id, anio, director, SINOPSIS, titulo, url_caratula)
VALUES 
(1, 2013, 'Alex Garland', 'Segunda aparición de Alex Garland en esta lista tras Devs. El punto de partida de las dos es similar: un joven ingenuo se introduce en una empresa de tecnología. El desarrollo muy diferente, aunque las conclusiones en ambos casos nos alertan del peligro de jugar a ser dioses. ', 'Ex Machina', 'https://m.media-amazon.com/images/M/MV5BNDlmMTJiZTgtNjk2YS00YzBkLThkZjQtZDEwYzJlMzkyOGY5XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg'),
(2, 2014, 'Richard Linklater', 'Linklater se ganó los elogios de medio mundo por su ambición y delicadeza al capturar la esencia misma del séptimo arte, el paso del tiempo. El crecimiento de Mason desde los 6 a los 18 años es toda una aventura cinematográfica, en la que obviamos los momentos más dramáticos para centrarnos en lo que deja el paso de los años. Let me go.', 'Boyhood', 'https://pics.filmaffinity.com/boyhood-954973569-large.jpg'),
(3, 2014, 'Colin Trevorrow', 'Tres empleados de una revista de investigación descubren un anuncio en el que un hombre busca un compañero para viajar en el tiempo. Uno de ellos queda fascinado por la idea y decide investigar qué hay detrás de la persona que ha escrito ese anuncio.', 'Seguridad no garantizada', 'https://es.web.img3.acsta.net/pictures/14/03/25/15/43/016246.jpg'),
(4, 1994, 'Frank Darabont', 'Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the mans unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.', 'Cadena Perpetua', 'https://es.web.img3.acsta.net/medias/nmedia/18/74/26/88/20133359.jpg'),
(5, 1994, 'Kevin Smith', 'Auténtico éxito del indie que conectó con miles de jóvenes debido a sus inspirados, encendidos y soeces diálogos. \'Clerks\' es una continua sucesión de personajes carismáticos que se mueven sobre un guion tan inspirado como nunca más fue capaz de repetir Kevin Smith.', 'Clerks', 'https://www.ecartelera.com/carteles/400/441/003_p.jpg'),
(6, 2010, 'Kim Jee-woon', 'Kyung-chul es un psicópata peligroso que mata por placer. Ha cometido asesinatos en serie infernales con unos métodos diabólicos difíciles de imaginar. Sus víctimas son desde chicas jóvenes hasta niños. La policía lleva tiempo tras su rastro sin lograr capturarlo. Un día, su presa es Ju-yeon, la hija de un jefe de policía retirado, cuyo cadáver es hallado en un estado espantoso. El novio de la chica, Soo-hyun, un agente secreto, se propone dar personalmente con el asesino. Jura hacer todo lo que esté en su mano para vengarse del criminal, aún si eso conlleva que él mismo se convierta en un asesino monstruoso e inhumano.', 'Encontré al diablo', 'https://www.elespectadorimaginario.com/media/Septiembre11/Critica/encontre_al_diablo_cartel.jpg'),
(7, 2016, 'Matt Ross', 'Viggo Mortensen nos conquistó a todos con esta propuesta familiar que, entre risas, aventura y road movie de carácter iniciático, dejaba muchas reflexiones valiosas sobre la educación y la vida urbana. Es una de esas películas con encanto a las que volver con frecuencia nunca está de más.', 'Captain Fantastic', 'https://pics.filmaffinity.com/captain_fantastic-545150407-large.jpg'),
(8, 1988, 'Hayao Miyazaki', 'En los años 50, una familia japonesa se traslada al campo. Las dos hijas, Satsuki y Mei, entablan amistad con Totoro, un espíritu del bosque. El padre es un profesor universitario que estimula la imaginación de sus hijas relatándoles fábulas e historias mágicas sobre duendes, fantasmas y espíritus protectores de los hogares, mientras la madre se encuentra enferma en el hospital.', 'Mi vecino Totoro', 'https://m.media-amazon.com/images/M/MV5BMjg3ZmIyYWMtYmRmMC00YTcyLTgzMjItODk3Yjc4ZDc5ODE5XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg');
